//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTAlumniPortal_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public int id { get; set; }
        public string resumeLink { get; set; }
        public Nullable<int> studentId { get; set; }
    }
}
