//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTAlumniPortal_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hired_alumni
    {
        public int alumni_id { get; set; }
        public int organization_id { get; set; }
        public int job_id { get; set; }
        public string organizational_email { get; set; }
        public Nullable<System.DateTime> date_hired { get; set; }
    }
}
