//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTAlumniPortal_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_posting
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string skils { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<int> organizationId { get; set; }
        public Nullable<int> alumniId { get; set; }
    }
}
